name: lettera
description: Application can a bit modify text for your needs
version: 1.0.0+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.7.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  reorderable_grid_view: ^2.2.6
  shared_preferences: ^2.2.0
  window_manager: ^0.3.5

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700